### ISSUE TITLE
Overwriting of src

### ISSUE THREAD

**Issue by eracah** [mila-iqia/atari-representation-learning#44]
I ran into an issue where I did `pip install -e .` for this repo and then worked on another repo that had a module called `src`. `pip install -e .` seemed to put the src from this repo on the path, so any time I referred to src in my other project it would used this one

In commit 23c1ede3feb16d5c6007cb039855a9, I changed the instructions to `python setup.py install`, which will only put the aari module on the path.

Not sure how other repos, like gym, that recommend `pip install -e .` seem to avoid this issue

**Comment by ankeshanand** [comment]
Fixed in https://github.com/mila-iqia/atari-representation-learning/commit/dacd81686d339d41540b2789edee9ce4c4156341!
