### ISSUE TITLE
Should the weights and biases account be configurable?

### ISSUE THREAD

**Issue by DuaneNielsen** [mila-iqia/atari-representation-learning#53]
```
python -m scripts.run_probe --method infonce-stdim --env-name PongNoFrameskip-v4
```

Requires a weights and biases account.  OK.  Account created.

After setup, it seems that the account name (entity) is hardcoded.to "curl-atari"

```
wandb.init(project=args.wandb_proj, entity="curl-atari", tags=tags)
```

perhaps it should be something like 

```
wandb.init(project=args.wandb_proj, entity=args.wandb_entiti, tags=tags)
```

Or am I mistaken?

**Comment by ankeshanand** [comment]
Thanks for spotting! I have added made entity configurable like you suggested, with the default set to `None`. This means that runs will default to your username unless an entity is specified.

**Comment by DuaneNielsen** [comment]
Thanks, I'm now able to run the example.  Digging into the code now.....

Going to take some time to get my head around it, so I may go dark for a bit.  Thanks so much for the support!
