### ISSUE TITLE
Confusing comment about scaling frame observations

### ISSUE THREAD

**Issue by Xemnas0** [mila-iqia/atari-representation-learning#54]
In [https://github.com/mila-iqia/atari-representation-learning/blob/master/atariari/benchmark/envs.py](https://github.com/mila-iqia/atari-representation-learning/blob/master/atariari/benchmark/envs.py), line 85 it is written that the class GrayscaleWrapper
`"""Warp frames to 84x84 as done in the Nature paper and later work."""`, although in the paper it is written that you do not scale to 84x84. Does this function scale the observations?

Thank you

**Comment by ankeshanand** [comment]
Thanks for reporting this @Xemnas0. That docstring is not correct, as that function only converts observations to grayscale. It doesn't scale the observations.

I have updated the docstring to reflect the current behavior.
