### ISSUE TITLE
unused naff_fc_size parameter

### ISSUE THREAD

**Issue by AnxietyYoungPoet** [mila-iqia/atari-representation-learning#63]
https://github.com/mila-iqia/atari-representation-learning/blob/aa37bf5858ca267ea0a0615e1a727308d5628e0d/atariari/methods/no_action_feedforward_predictor.py#L28-L30
In  NaFFPredictor, the fc layer uses the feature_size from the encoder as the layer width, hence the naff_fc_size is left unused. Also, Sequential is used here, so it seems there might be multiple layers.

**Comment by eracah** [comment]
Oh good catch! I believe it was initially used, but then we realized to make the capacity the same as the VAE the "middle" FC layer could only be a feature_size x feature_size matrix. We'll remove that argument

**Comment by AnxietyYoungPoet** [comment]
@eracah Got it! Thanks for your clarification!
