### ISSUE TITLE
Ram annotation of (x, y) are not aligned 

### ISSUE THREAD

**Issue by happywu** [mila-iqia/atari-representation-learning#64]
Hi,

I've tried using the provided AtariARIWrapper to get the 'labels' for MsPacmanNoFrameskip-v4. 
However, when I draw the locations of player, enemy_sue, enemy_inky..., using ('player_x', 'player_y'), ('enemy_sue_x', 'enemy_sue_y'), there seems to be always certain offsets to the real location.

![image](https://user-images.githubusercontent.com/8135344/76263142-848ee480-6234-11ea-86cd-51cd8ae4a0c8.png)

![image](https://user-images.githubusercontent.com/8135344/76263169-95d7f100-6234-11ea-8b7a-15eb31bbd3bb.png)

How can get the aligned locations?
Thanks

**Comment by eracah** [comment]
Hi,
So the wrapper provides just the raw RAM values. The source code of the game then uses those values to render the sprites. Unfortunately, I don't know assembly code well enough to interpret this rendering process. See [issue 47](https://github.com/mila-iqia/atari-representation-learning/issues/47) for a longer answer on this topic. One thing you could do is find (by trial and error) what the offset is and then just add this offset to your code that draws the circles.
Hope this helps!

**Comment by ankeshanand** [comment]
@happywu We also found the mapping from RAM values to screen positions to be inconsistent across games, and also across different variables within each game. If you want to do this only for a particular game, you can try to deconstruct the encoding for that game using the disassemblies: http://www.bjars.com/disassemblies.html

**Comment by happywu** [comment]
Thanks, I think manual hack the offsets for certain game would work.
