### ISSUE TITLE
Generating Enough Episodes for Tennis

### ISSUE THREAD

**Issue by adamtupper** [mila-iqia/atari-representation-learning#65]
I've been trying to generate the same number of frames described in the paper for probing evaluations (35,000 train; 5,000 validation; 10,000 test), but for Tennis I am unable to do so because of the large number of duplicates in the collected episodes. May ask are how you were able to for the paper?

I've tried collecting episodes with different random seeds and up to 400,000 steps (to try and account for duplicates), but so far to no avail. I've succeeded in generating episodes for other games but just not Tennis. I believe this might be because the agent spends the majority of episodes refusing to serve the ball (an issue I've come across previously before).

```python
tr_episodes, val_episodes,\
tr_labels, val_labels,\
test_episodes, test_labels = get_episodes(env_name='TennisNoFrameskip-v4', 
    steps=50000, 
    collect_mode="pretrained_ppo",
    seed=seed)
```

**Comment by ankeshanand** [comment]
Yeah, it seems PPO doesn't do well on Tennis and probably converges to a degenerate policy. We didn't have the issue with duplicates when using a random policy though, and for PPO we just used as many non-duplicates for test as we could get, it's def not ideal.

Depending on your use-case, I guess you could a pretrained DQN / C51 (those seem to do well on Tennis), with a high enough epsilon to get diverse samples.

**Comment by adamtupper** [comment]
No worries, thanks for the clarification!
